### ISSUE TITLE
A gleeunit-specific `given`?

### ISSUE THREAD

**Issue by drewolson** [mooreryan/qcheck_gleeunit_utils#1]
Hello!

First of all, I'm a huge fan of `qcheck`. I've used it to test my library [clip](https://github.com/drewolson/clip) and I've been very impressed!

In using `qcheck`, I found I wanted to be able to use assertions from `gleeunit/should` in my `qcheck` properties. I ended up writing a small [helper](https://github.com/drewolson/clip/blob/66b39642f7b31660c20a09c58759b25eee9a85a4/test/qcheck/qtest/util.gleam#L11-L15) that allows me to do this (though I think the error messages could be better if it was natively integrated). You can see an example usage [here](https://github.com/drewolson/clip/blob/66b39642f7b31660c20a09c58759b25eee9a85a4/test/clip/arg_test.gleam#L50-L62).

Do you think something like this might be worth adding to either `qcheck` itself or `qcheck_gleeunit_utils`?

**Comment by mooreryan** [comment]
Hi, thanks for bringing this up.

It's interesting you mention wanting the `should` style.  Originally, qcheck did use the `should` style assertions, but it was changed to the way it is now based on discussions here: https://github.com/mooreryan/gleam_qcheck/issues/1. Maybe something like your wrapper could be included in this package though, if it would be helpful.

Regarding better error messages, it's also a good question.  I thought it would be nice to provide good diffs, e.g., something like this: https://github.com/maxdeviant/startest/issues/8, which I grafted on to my fork of the startest library.  I even had a half-baked solution for qcheck, but it needs more work.

Here is a bit more on that diffing if you're curious.

- https://github.com/giacomocavalieri/birdie/issues/13
- https://github.com/giacomocavalieri/pretty_diff

**Comment by drewolson** [comment]
Interestingly, https://github.com/mooreryan/gleam_qcheck/issues/1 seems to argue for panic-style assertions, not `Bool`s, right? Perhaps I'm misreading. Edit: when I'm asking for `should`-style assertions, I mean literally using `gleeunit/should`, but _within_ the body of a `given` callback. This means `given`'s callback needs to be an `fn(a) -> Nil`, not an `fn(a) -> Bool`. As lpil states, this also allows for multiple assertions and short circuiting.

Regarding error messages, I actually think that `gleeunit/should` assertions provide great error messages -- if you could simply catch them and add to the `String` they produce with the `exceptions` package, you could show the initial and shrunk values. I think that might be enough for everything to "just work" nicely. That said, my wrapper is working fine for me now. Looking forward to watching this library in the future!

**Comment by mooreryan** [comment]
Ohh yes you are correct, I misread your comment, sorry about that!  But yes you're right if the `given` callback returned `Nil` it would work with the gleeunit's assertions.  You could imagine adding a `run_nil` or something to go with `run` and `run_result`.  Or potentially just `run` would take a callback that returns `Nil` and then have `run_bool` and `run_result`.  Or potentially unified in some other way.  (The main reason the default is a bool returning callback is because that is the way I like to write properties, but it could change later if necessary.)

> Interestingly, https://github.com/mooreryan/gleam_qcheck/issues/1 seems to argue for panic-style assertions, not Bools, right?

And yes you're right about this as well.  For now, I let panics trigger shrinking as well as the bool returning, but it's probably something I will revisit in the future.

> Regarding error messages, I actually think that gleeunit/should assertions provide great error messages

Interesting, potentially I should revisit this strategy.

> my wrapper is working fine for me now

^ Given that, I will go ahead and close this issue for now, but I appreciate you bringing it up!
